### ISSUE TITLE
Gisjobsmap.com isn't working

### ISSUE THREAD

**Issue by jacalata** [ishiland/ishiland.github.io#1]
Hey, I have been looking at your site gisjobsmap.com and noticed that it appears to hang while loading jobs - the loading screen never goes away. Couldn't find an email address so thought this was the best way to let you know.

**Comment by ishiland** [comment]
Hey, sorry about the site. It looks like it was compromised this week from
some sort of malicious activity. I will work on restoring it this weekend.
Thanks for your patience.

**Comment by jacalata** [comment]
No problem - it's a cool site and I understand that it's just a side project :) Good luck restoring it!
